apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstack-config
  namespace: bookstack-lab
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: app
    app.kubernetes.io/part-of: bookstack-lab
    app.kubernetes.io/managed-by: manual-lab
    app.kubernetes.io/environment: lab
data:
  TZ: "Europe/Berlin"
  BOOKSTACK_APP_URL: "http://bookstack.local"
  BOOKSTACK_DB_HOST: "bookstack-db"
  BOOKSTACK_DB_PORT: "3306"
  BOOKSTACK_DB_NAME: "bookstack"
  BOOKSTACK_DB_USER: "bookstack"
