apiVersion: v1
kind: Secret
metadata:
  name: bookstack-secret
  namespace: bookstack-lab
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/part-of: bookstack-lab
    app.kubernetes.io/managed-by: manual-lab
    app.kubernetes.io/environment: lab
type: Opaque
stringData:
  BOOKSTACK_APP_KEY: "base64:tusbAlaRtf4sJ+H9o39U+weGQKf3fjc2D2neZ+Rdi4Q="
  BOOKSTACK_DB_PASSWORD: "password"
  MARIADB_ROOT_PASSWORD: "root"
