apiVersion: v1
kind: Service
metadata:
  name: bookstack-db
  namespace: bookstack-lab
  labels:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: db
    app.kubernetes.io/part-of: bookstack-lab
    app.kubernetes.io/managed-by: manual-lab
    app.kubernetes.io/environment: lab
spec:
  selector:
    app.kubernetes.io/name: bookstack
    app.kubernetes.io/component: db
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306